version: '3.0'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000
      - MONGODB_URL=mongodb://root:password@mongodb:27017/
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - REACT_APP_CONNECT_BACKEND=http://localhost:8000
    ports:
      - 3000:3000
    depends_on:
      - backend
    
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongodb:27017/
    depends_on:
      - mongodb